FROM gotson/komga:0.153.0

RUN find /app/BOOT-INF/classes/public/css -type f -name app.*.css -exec sh -c "echo \".v-card__text.px-2{padding: 6px}.v-card__subtitle.pa-2.pb-1{font-family:'Roboto Condensed',sans-serif;height:4.5em !important;line-height:1.3em;-webkit-line-clamp:3 !important}\" >> {}" \;


